# Site
name: "Technorage"
title: "Technorage"
description: "Where I rage about technology and stuff!"
logo: "assets/images/logo.png"
favicon: "assets/images/logo.png"
title_image: "assets/images/logo.png"
google_analytics: "UA-74370272-6"
# disqus: "deepu-tech"
mailchimp-list: 'https://tech.us7.list-manage.com/subscribe/post?u=00729f6c6d6bb180801b9484e&amp;id=f521dede4b'
permalink: /:title/
url: "https://deepu.tech" # the base hostname & protocol for your site
repository: "deeputech/deeputech.github.io"
twitter_username: "deepu105"
# Staticman comments (full configuration in staticman.yml)
staticman:
  branch: "site_src"

# Authors
authors:
    deepu:
        name: Deepu
        display_name: Deepu K Sasidharan
        gravatar: 7f408bc67dc9ae3b288ee92d16d3c4c2 # md5 hash of d4udts@gmail.com
        email: deepu.k.sasidharan@gmail.com
        web: https://www.deepu.tech
        twitter: https://twitter.com/deepu105
        mastodon: https://mastodon.social/@deepu105
        description: "JHipster co-lead, Java, JS, Cloud Native Advocate, Developer Advocate @ Adyen, Author, Speaker, Software craftsman. Loves simple & beautiful code. bit.ly/JHIPSTER-BOOKS"

# Plugins
plugins:
    - jekyll-paginate-v2
    - jekyll-sitemap
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-archives

defaults:
    - scope:
          path: "" # an empty string here means all files in the project
          type: "posts" # previously `post` in Jekyll 2.2.
      values:
          layout: "post"
    - scope:
          path: "" # an empty string here means all files in the project
          type: "posts" # previously `post` in Jekyll 2.2.
      values:
          author: "deepu"
          toc: true

# Archives
jekyll-archives:
    enabled:
        - categories
    layout: archive
    permalinks:
        category: "/category/:name/"

# Pagination Settings
pagination:
    enabled: true
    per_page: 6
    permalink: "/page/:num/"
    title: " - page :num"
    limit: 0
    sort_field: "date"
    sort_reverse: true

# Other
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    syntax_highlighter: rouge
    syntax_highlighter_opts:
        block:
            guess_lang: true
            line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

include: ["_pages"]
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
    - changelog.md
    - LICENSE.txt
    - Gemfile
    - Gemfile.lock
    - node_modules
    - vendor/
    - mediumish-theme-jekyll/
    - temp/
