on:
  push:
    branches: ["site_src"]

name: Publish site

jobs:
  # Workaround for making Github Actions skip based on commit message `[skip ci]`
  # Source https://gist.github.com/ybiquitous/c80f15c18319c63cae8447a3be341267
  # prepare:
  #   runs-on: ubuntu-latest
  #   if: |
  #     !contains(format('{0} {1} {2}', github.event.head_commit.message, github.event.pull_request.title, github.event.pull_request.body), '[skip ci]')
  #   steps:
  #     - run: |
  #         cat <<'MESSAGE'
  #         github.event_name: ${{ toJson(github.event_name) }}
  #         github.event:
  #         ${{ toJson(github.event) }}
  #         MESSAGE
  publish:
    name: Publish
    runs-on: ubuntu-latest
    # needs: prepare
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/setup-node@v2
      - run: npm install
      - run: git config user.email "d4udts@gmail.com"
      - run: git config user.name "Deepu K Sasidharan"
      - run: ./publish.sh -sc
        env:
          DEV_API_KEY: ${{ secrets.DEV_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

