on:
  push:
    branches: ["site_src"]

name: Publish site

jobs:
  # Workaround for making Github Actions skip based on commit message `[skip ci]`
  # Source https://gist.github.com/ybiquitous/c80f15c18319c63cae8447a3be341267
  # prepare:
  #   runs-on: ubuntu-latest
  #   if: |
  #     !contains(format('{0} {1} {2}', github.event.head_commit.message, github.event.pull_request.title, github.event.pull_request.body), '[skip ci]')
  #   steps:
  #     - run: |
  #         cat <<'MESSAGE'
  #         github.event_name: ${{ toJson(github.event_name) }}
  #         github.event:
  #         ${{ toJson(github.event) }}
  #         MESSAGE
  publish:
    name: Publish
    runs-on: ubuntu-latest
    # needs: prepare
    steps:
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/setup-node@v2
      # - name: install dependencies & build site
      #   uses: limjh16/jekyll-action-ts@v2
      #   with:
      #     enable_cache: true
      # These dependencies are required for `clipboard`
      # - run: sudo apt-get install -y -qq libxcb1-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev
      - run: git clone https://github.com/deeputech/deeputech.github.io.git
      - run: cd deeputech.github.io
      - run: npm install
      - run: ./publish.sh -sc
        env:
          DEV_API_KEY: ${{ secrets.DEV_API_KEY }}

